import type { ObjectKeyOrder } from '@alexaegis/common';

export const DEFAULT_PACKAGE_JSON_SORTING_PREFERENCE: ObjectKeyOrder = [
	'name',
	'displayName',
	'description',
	'version',
	'license',
	'private',
	'author',
	'homepage',
	'repository',
	'bugs',
	'keywords',
	'type',
	'config',
	'publishConfig',
	'.*',
	'engines',
	'packageManager',
	'workspaces',
	{ key: 'scripts', order: ['build.*', 'lint.*', 'test.*'] },
	{ key: 'exports', order: [{ key: '.*', order: ['types', '.*'] }] },
	'bin',
	'dependencies',
	'peerDependencies',
	'optonalDependencies',
	'devDependencies',
];
